spring :
  datasource :
    url : jdbc:mysql://localhost:3306/student_crm?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 2010
  jpa:
    hibernate:
      ddl-auto : update