student:
    institute : ICET-QUALITY-TEAM

spring :
  datasource :
    url : jdbc:mysql://:3306/institute_crm
    username: admin
    password: SKDLJFLSD@123
  jpa:
    hibernate:
      ddl-auto : update
